language: lisp
dist: xenial
env: PREFIX="$(pwd)/sbcl"
     SBCL_HOME="$(pwd)/sbcl/lib/sbcl"
     SBCL="$(pwd)/sbcl/bin/sbcl"
     SBCL_OPTIONS="--noinform --no-userinit"

install:
  - curl -L "${SBCL_DOWNLOAD_URL}" | tar -xj
  - ( cd sbcl-* && INSTALL_ROOT="${PREFIX}" sh install.sh )

  - curl -o cl "${CL_LAUNCH_DOWNLOAD_URL}"
  - chmod +x cl

  - curl -o quicklisp.lisp "${QUICKLISP_DOWNLOAD_URL}"
  - ./cl -L quicklisp.lisp '(quicklisp-quickstart:install)'

script:
  - (
      cd "${HOME}/quicklisp/local-projects"
        && git clone -b future https://github.com/scymtym/model.transform.trace
        && git clone -b future https://github.com/scymtym/language.yaml
        && git clone -b future https://github.com/scymtym/text.source-location
        && git clone https://code.cor-lab.de/git/rosetta.git.cl
        && git clone https://code.cor-lab.de/git/rosetta.git.project-cl
    )
  - ./cl
      -S '(:source-registry (:directory "'$(pwd)'/lib/jenkins.api") (:directory "'$(pwd)'") :ignore-inherited-configuration)'
      -Q
      -s build-generator/test
      '(or (mapc (function asdf:test-system)
                 (list :build-generator/test))
            (uiop:quit -1))'
  - ./cl
      -S '(:source-registry (:directory "'$(pwd)'/lib/jenkins.api") (:directory "'$(pwd)'") :ignore-inherited-configuration)'
      -Q
      -s build-generator.commandline-interface
      --dump ! --output build-generator -r "build-generator.commandline-interface:main"
  - ./build-generator version -c 1
  - ./build-generator || true
